# Generated by Django 4.1.7 on 2023-03-01 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_guitar_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guitar',
            name='numPickups',
        ),
        migrations.RemoveField(
            model_name='guitar',
            name='typePickups',
        ),
        migrations.RemoveField(
            model_name='guitar',
            name='year',
        ),
    ]
