# Generated by Django 4.1.7 on 2023-03-02 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_remove_guitar_numpickups_remove_guitar_typepickups_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restringing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('restring', models.CharField(choices=[('NP', 'Nickel-plated steel'), ('PN', 'Pure nickel'), ('SS', 'Stainless steel'), ('NY', 'Nylon')], default='NP', max_length=2)),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.guitar')),
            ],
        ),
    ]
