# Generated by Django 4.1.7 on 2023-03-02 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_restringing'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restringing',
            old_name='cat',
            new_name='guitar',
        ),
    ]
