# Generated by Django 4.1.7 on 2023-03-02 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_rename_string_restringing_string'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('catagory', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterModelOptions(
            name='restringing',
            options={'ordering': ['-date']},
        ),
    ]
