# Generated by Django 4.1.7 on 2023-03-02 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_pedal_alter_restringing_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='guitar',
            name='pedals',
            field=models.ManyToManyField(to='main_app.pedal'),
        ),
    ]
