# Generated by Django 4.1.7 on 2023-03-05 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_guitar_pedals'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedal',
            old_name='catagory',
            new_name='category',
        ),
    ]
